part of 'polarization_input.dart';

  const List<Map<String, dynamic>> preset = [{
  // 'omega': '100',
  'beta': '100',
  'EtEx': '10',
  'EtEy': '10',
  'EtPhix': '-120',
  'EtPhiy': '150',
  'EtPhixUnit': AngleUnit.deg,
  'EtPhiyUnit': AngleUnit.deg,
  'EtExTf': TriFunc.cos,
  'EtEyTf': TriFunc.sin,
  'EpExRe': '0',
  'EpExIm': '0',
  'EpEyRe': '0',
  'EpEyIm': '-78',
  'EpExAbs': '0',
  'EpExArg': '0',
  'EpEyAbs': '78',
  'EpEyArg': '-90',
  'EpExFmt': ComplexFormat.polar,
  'EpEyFmt': ComplexFormat.polar,
  'EpExAngleUnit': AngleUnit.deg,
  'EpEyAngleUnit': AngleUnit.deg,
  'MtHx': '0',
  'MtHy': '1',
  'MtPhix': '0',
  'MtPhiy': '0',
  'MtPhixUnit': AngleUnit.npi,
  'MtPhiyUnit': AngleUnit.npi,
  'MtHxTf': TriFunc.cos,
  'MtHyTf': TriFunc.cos,
  'MpHxRe': '0',
  'MpHxIm': '0',
  'MpHyRe': '1',
  'MpHyIm': '0',
  'MpHxAbs': '0',
  'MpHxArg': '0',
  'MpHyAbs': '1',
  'MpHyArg': '0',
  'MpHxFmt': ComplexFormat.rect,
  'MpHyFmt': ComplexFormat.rect,
  'MpHxAngleUnit': AngleUnit.npi,
  'MpHyAngleUnit': AngleUnit.npi,
  'BetaSign': Sign.minus,
  'SourceType':SourceField.et,
  //// new parameters
  'freq': '385',
  'freqUnit': FreqUnit.mhz,
  'epsr_1':'2.6',
  'epsr_2':'1',
  'mur_1':'1',
  'mur_2':'1',
  'sigma_2':'0',
  'thetaI':'31.81',
  'thetaIUnit':AngleUnit.deg,
  'givenFreq': 'true',
  },
  

  {
  // 'omega': '100',
  'beta': '100',
  'EtEx': '10',
  'EtEy': '10',
  'EtPhix': '-120',
  'EtPhiy': '150',
  'EtPhixUnit': AngleUnit.deg,
  'EtPhiyUnit': AngleUnit.deg,
  'EtExTf': TriFunc.cos,
  'EtEyTf': TriFunc.sin,
  'EpExRe': '5',
  'EpExIm': '0',
  'EpEyRe': '0',
  'EpEyIm': '-5',
  'EpExAbs': '5',
  'EpExArg': '0',
  'EpEyAbs': '5',
  'EpEyArg': '-90',
  'EpExFmt': ComplexFormat.polar,
  'EpEyFmt': ComplexFormat.polar,
  'EpExAngleUnit': AngleUnit.deg,
  'EpEyAngleUnit': AngleUnit.deg,
  'MtHx': '0',
  'MtHy': '1',
  'MtPhix': '0',
  'MtPhiy': '0',
  'MtPhixUnit': AngleUnit.npi,
  'MtPhiyUnit': AngleUnit.npi,
  'MtHxTf': TriFunc.cos,
  'MtHyTf': TriFunc.cos,
  'MpHxRe': '0',
  'MpHxIm': '0',
  'MpHyRe': '1',
  'MpHyIm': '0',
  'MpHxAbs': '0',
  'MpHxArg': '0',
  'MpHyAbs': '1',
  'MpHyArg': '0',
  'MpHxFmt': ComplexFormat.rect,
  'MpHyFmt': ComplexFormat.rect,
  'MpHxAngleUnit': AngleUnit.npi,
  'MpHyAngleUnit': AngleUnit.npi,
  'BetaSign': Sign.minus,
  'SourceType':SourceField.et,
  //// new parameters
  'freq': '318',
  'freqUnit': FreqUnit.mhz,
  'epsr_1':'2.25',
  'epsr_2':'1',
  'mur_1':'1',
  'mur_2':'1',
  'sigma_2':'0',
  'k_x': '8',
  'k_z': '6',
  'givenFreq': 'false',
  },
  ];

// enum Preset {
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': ,
//     //   'EtEy': ,
//     //   'EtPhix': ,
//     //   'EtPhiy': ,
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': ,
//     //   'EpExIm': ,
//     //   'EpEyRe': ,
//     //   'EpEyIm': ,
//     //   'EpExAbs': ,
//     //   'EpExArg': ,
//     //   'EpEyAbs': ,
//     //   'EpEyArg': ,
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': ,
//     //   'MtHy': ,
//     //   'MtPhix': ,
//     //   'MtPhiy': ,
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': ,
//     //   'MpHxIm': ,
//     //   'MpHyRe': ,
//     //   'MpHyIm': ,
//     //   'MpHxAbs': ,
//     //   'MpHxArg': ,
//     //   'MpHyAbs': ,
//     //   'MpHyArg': ,
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//   linear([
//     // { // horizontal
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '0',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '0',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '0',
//     //   'EpEyArg': '0',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '0',
//     //   'MtHy': '1',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '0',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '1',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '0',
//     //   'MpHxArg': '0',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     //   'BetaSign': Sign.plus,
//     // },
//     // { // vertical
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '0',
//     //   'EtEy': '1',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '0',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '1',
//     //   'EpEyIm': '0',
//     //   'EpExAbs': '0',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '0',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '0',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '-1',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '0',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '1',
//     //   'MpHxArg': '1',
//     //   'MpHyAbs': '0',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     //   'BetaSign': Sign.minus,
//     // },
//     // { // 45 deg /
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '1',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '1',
//     //   'EpEyIm': '0',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '0',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '1',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '-1',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '1',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '1',
//     //   'MpHxArg': '1',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // { // 45 deg \
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '-1',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '-1',
//     //   'EpEyIm': '0',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '1',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '1',
//     //   'MtHy': '1',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '1',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '1',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '1',
//     //   'MpHxArg': '0',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // }
//     { // Tutorial-1-i
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '10',
//       'EtEy': '10',
//       'EtPhix': '-120',
//       'EtPhiy': '150',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.sin,
//       'EpExRe': '1',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '0',
//       'EpExAbs': '10',
//       'EpExArg': '-120',
//       'EpEyAbs': '10',
//       'EpEyArg': '60',
//       'EpExFmt': ComplexFormat.polar,
//       'EpEyFmt': ComplexFormat.polar,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.npi,
//       'MtPhiyUnit': AngleUnit.npi,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.minus,
//       'SourceType':SourceField.et,
//     },
//     { // Tutorial-1-i
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '10',
//       'EtEy': '-10',
//       'EtPhix': '-120',
//       'EtPhiy': '150',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.sin,
//       'EpExRe': '1',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '0',
//       'EpExAbs': '10',
//       'EpExArg': '-120',
//       'EpEyAbs': '10',
//       'EpEyArg': '-120',
//       'EpExFmt': ComplexFormat.polar,
//       'EpEyFmt': ComplexFormat.polar,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.npi,
//       'MtPhiyUnit': AngleUnit.npi,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.minus,
//       'SourceType':SourceField.et,
//     },
//     { // Tutorial-1-i
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '10',
//       'EtEy': '10',
//       'EtPhix': '-120',
//       'EtPhiy': '150',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.sin,
//       'EpExRe': '1',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '0',
//       'EpExAbs': '10',
//       'EpExArg': '-120',
//       'EpEyAbs': '10',
//       'EpEyArg': '60',
//       'EpExFmt': ComplexFormat.polar,
//       'EpEyFmt': ComplexFormat.polar,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.npi,
//       'MtPhiyUnit': AngleUnit.npi,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.minus,
//       'SourceType':SourceField.et,
//     }
//   ]),

//   elliptical([
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '2',
//     //   'EtEy': '1',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '0.5',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '2',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '1',
//     //   'EpExAbs': '2',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '0.5',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '2',
//     //   'MtPhix': '0.5',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '0',
//     //   'MpHxIm': '-1',
//     //   'MpHyRe': '2',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '-1',
//     //   'MpHxArg': '0.5',
//     //   'MpHyAbs': '2',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '2',
//     //   'EtEy': '1',
//     //   'EtPhix': '0.5',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '2',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '1',
//     //   'EpExAbs': '2',
//     //   'EpExArg': '0.5',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '0',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '2',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0.5',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '-1',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '0',
//     //   'MpHyIm': '2',
//     //   'MpHxAbs': '-1',
//     //   'MpHxArg': '0',
//     //   'MpHyAbs': '2',
//     //   'MpHyArg': '0.5',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '2',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '0.5',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '2',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '2',
//     //   'EpEyArg': '0.5',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-2',
//     //   'MtHy': '1',
//     //   'MtPhix': '0.5',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '0',
//     //   'MpHxIm': '-2',
//     //   'MpHyRe': '1',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '-2',
//     //   'MpHxArg': '0.5',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '2',
//     //   'EtPhix': '0.5',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '2',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0.5',
//     //   'EpEyAbs': '2',
//     //   'EpEyArg': '0',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-2',
//     //   'MtHy': '1',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0.5',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '-2',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '0',
//     //   'MpHyIm': '1',
//     //   'MpHxAbs': '-2',
//     //   'MpHxArg': '0',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0.5',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '2',
//     //   'EtPhix': '0.5',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '4',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '-3',
//     //   'EpExAbs': '4',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '3',
//     //   'EpEyArg': '-0.5',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-2',
//     //   'MtHy': '1',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0.5',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '-2',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '0',
//     //   'MpHyIm': '1',
//     //   'MpHxAbs': '-2',
//     //   'MpHxArg': '0',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0.5',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     { // Tutorial-1-iii
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '30',
//       'EtEy': '40',
//       'EtPhix': '20',
//       'EtPhiy': '-70',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.cos,
//       'EpExRe': '1',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '0',
//       'EpExAbs': '30',
//       'EpExArg': '20',
//       'EpEyAbs': '40',
//       'EpEyArg': '-70',
//       'EpExFmt': ComplexFormat.polar,
//       'EpEyFmt': ComplexFormat.polar,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.npi,
//       'MtPhiyUnit': AngleUnit.npi,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.minus,
//       'SourceType':SourceField.ep,
//     },
//     { // Tutorial-1-iii
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '4',
//       'EtEy': '3',
//       'EtPhix': '0',
//       'EtPhiy': '-90',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.cos,
//       'EpExRe': '4',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '-3',
//       'EpExAbs': '30',
//       'EpExArg': '20',
//       'EpEyAbs': '40',
//       'EpEyArg': '-70',
//       'EpExFmt': ComplexFormat.rect,
//       'EpEyFmt': ComplexFormat.rect,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.npi,
//       'MtPhiyUnit': AngleUnit.npi,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.minus,
//       'SourceType':SourceField.ep,
//     },
//     { // Tutorial-1-iii
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '4',
//       'EtEy': '3',
//       'EtPhix': '0',
//       'EtPhiy': '0',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.cos,
//       'EpExRe': '4',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '3',
//       'EpExAbs': '30',
//       'EpExArg': '20',
//       'EpEyAbs': '40',
//       'EpEyArg': '-70',
//       'EpExFmt': ComplexFormat.rect,
//       'EpEyFmt': ComplexFormat.rect,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.npi,
//       'MtPhiyUnit': AngleUnit.npi,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.minus,
//       'SourceType':SourceField.ep,
//     },
//   ]),

//   circular([
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '1',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '0.5',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '1',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '0.5',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '1',
//     //   'MtPhix': '0.5',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '0',
//     //   'MpHxIm': '-1',
//     //   'MpHyRe': '1',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '-1',
//     //   'MpHxArg': '0.5',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '1',
//     //   'EtPhix': '0.5',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '0',
//     //   'EpExIm': '1',
//     //   'EpEyRe': '1',
//     //   'EpEyIm': '0',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0.5',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '0',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '1',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '0.5',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '-1',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '0',
//     //   'MpHyIm': '1',
//     //   'MpHxAbs': '-1',
//     //   'MpHxArg': '0',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0.5',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '1',
//     //   'EtPhix': '1.5',
//     //   'EtPhiy': '0',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '0',
//     //   'EpExIm': '-1',
//     //   'EpEyRe': '1',
//     //   'EpEyIm': '0',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '1.5',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '0',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '1',
//     //   'MtPhix': '0',
//     //   'MtPhiy': '1.5',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '-1',
//     //   'MpHxIm': '0',
//     //   'MpHyRe': '0',
//     //   'MpHyIm': '-1',
//     //   'MpHxAbs': '-1',
//     //   'MpHxArg': '0',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '1.5',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '1',
//     //   'EtEy': '1',
//     //   'EtPhix': '0',
//     //   'EtPhiy': '1.5',
//     //   'EtPhixUnit': AngleUnit.npi,
//     //   'EtPhiyUnit': AngleUnit.npi,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.cos,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '-1',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '1.5',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '1',
//     //   'MtPhix': '1.5',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '0',
//     //   'MpHxIm': '1',
//     //   'MpHyRe': '1',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '-1',
//     //   'MpHxArg': '1.5',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     // {
//     //   'omega': defaultOmega,
//     //   'beta': defaultBeta,
//     //   'EtEx': '10',
//     //   'EtEy': '-10',
//     //   'EtPhix': '30',
//     //   'EtPhiy': '-150',
//     //   'EtPhixUnit': AngleUnit.deg,
//     //   'EtPhiyUnit': AngleUnit.deg,
//     //   'EtExTf': TriFunc.cos,
//     //   'EtEyTf': TriFunc.sin,
//     //   'EpExRe': '1',
//     //   'EpExIm': '0',
//     //   'EpEyRe': '0',
//     //   'EpEyIm': '-1',
//     //   'EpExAbs': '1',
//     //   'EpExArg': '0',
//     //   'EpEyAbs': '1',
//     //   'EpEyArg': '1.5',
//     //   'EpExFmt': ComplexFormat.rect,
//     //   'EpEyFmt': ComplexFormat.rect,
//     //   'EpExAngleUnit': AngleUnit.npi,
//     //   'EpEyAngleUnit': AngleUnit.npi,
//     //   'MtHx': '-1',
//     //   'MtHy': '1',
//     //   'MtPhix': '1.5',
//     //   'MtPhiy': '0',
//     //   'MtPhixUnit': AngleUnit.npi,
//     //   'MtPhiyUnit': AngleUnit.npi,
//     //   'MtHxTf': TriFunc.cos,
//     //   'MtHyTf': TriFunc.cos,
//     //   'MpHxRe': '0',
//     //   'MpHxIm': '1',
//     //   'MpHyRe': '1',
//     //   'MpHyIm': '0',
//     //   'MpHxAbs': '-1',
//     //   'MpHxArg': '1.5',
//     //   'MpHyAbs': '1',
//     //   'MpHyArg': '0',
//     //   'MpHxFmt': ComplexFormat.rect,
//     //   'MpHyFmt': ComplexFormat.rect,
//     //   'MpHxAngleUnit': AngleUnit.npi,
//     //   'MpHyAngleUnit': AngleUnit.npi,
//     // },
//     { // Tutorial-1-ii
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '10',
//       'EtEy': '10',
//       'EtPhix': '-120',
//       'EtPhiy': '-30',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.cos,
//       'EpExRe': '1',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '0',
//       'EpExAbs': '10',
//       'EpExArg': '-120',
//       'EpEyAbs': '10',
//       'EpEyArg': '-30',
//       'EpExFmt': ComplexFormat.polar,
//       'EpEyFmt': ComplexFormat.polar,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.npi,
//       'MtPhiyUnit': AngleUnit.npi,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.plus,
//       'SourceType':SourceField.et,
//     },
//     { // Tutorial-2
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '4.45',
//       'EtEy': '4.45',
//       'EtPhix': '0',
//       'EtPhiy': '-90',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.cos,
//       'EpExRe': '4.45',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '-4.45',
//       'EpExAbs': '30',
//       'EpExArg': '20',
//       'EpEyAbs': '40',
//       'EpEyArg': '-70',
//       'EpExFmt': ComplexFormat.rect,
//       'EpEyFmt': ComplexFormat.rect,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.deg,
//       'MtPhiyUnit': AngleUnit.deg,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.minus,
//       'SourceType':SourceField.ep,
//     },
//     { // post-Survey
//       'omega': defaultOmega,
//       'beta': defaultBeta,
//       'EtEx': '10',
//       'EtEy': '-10',
//       'EtPhix': '30',
//       'EtPhiy': '30',
//       'EtPhixUnit': AngleUnit.deg,
//       'EtPhiyUnit': AngleUnit.deg,
//       'EtExTf': TriFunc.cos,
//       'EtEyTf': TriFunc.sin,
//       'EpExRe': '4.45',
//       'EpExIm': '0',
//       'EpEyRe': '0',
//       'EpEyIm': '-4.45',
//       'EpExAbs': '10',
//       'EpExArg': '30',
//       'EpEyAbs': '10',
//       'EpEyArg': '120',
//       'EpExFmt': ComplexFormat.polar,
//       'EpEyFmt': ComplexFormat.polar,
//       'EpExAngleUnit': AngleUnit.deg,
//       'EpEyAngleUnit': AngleUnit.deg,
//       'MtHx': '0',
//       'MtHy': '1',
//       'MtPhix': '0',
//       'MtPhiy': '0',
//       'MtPhixUnit': AngleUnit.deg,
//       'MtPhiyUnit': AngleUnit.deg,
//       'MtHxTf': TriFunc.cos,
//       'MtHyTf': TriFunc.cos,
//       'MpHxRe': '0',
//       'MpHxIm': '0',
//       'MpHyRe': '1',
//       'MpHyIm': '0',
//       'MpHxAbs': '0',
//       'MpHxArg': '0',
//       'MpHyAbs': '1',
//       'MpHyArg': '0',
//       'MpHxFmt': ComplexFormat.rect,
//       'MpHyFmt': ComplexFormat.rect,
//       'MpHxAngleUnit': AngleUnit.npi,
//       'MpHyAngleUnit': AngleUnit.npi,
//       'BetaSign': Sign.plus,
//       'SourceType':SourceField.et,
//     }
//   ]),
//   ;

//   static const String defaultOmega = '1000000';  // 1 Mrad/s
//   static const String defaultBeta = '0.003333'; // beta = 2 pi / lambda = omega / vp

//   final List<Map<String, dynamic>> profiles;

//   const Preset(this.profiles);
// }